### ISSUE TITLE
Python dependencies resolution issue

### ISSUE THREAD

**Issue by varnie** [glasswall-sre/serverless-victoria#9]
The following happens from time to time when one adds a new Python dependency using `pipenv` utility or attempts to perform deployment (i.e. `sls deploy`):

> Serverless: Generating requirements.txt from Pipfile...
>  
>   Error --------------------------------------------------
>  
>   Error: Pipfile.lock (6788ab) out of date, updating to (1dbf3d)…
>   Locking [dev-packages] dependencies…
> ⠋ Locking..✔ Success! 
>   Locking [packages] dependencies…
> ⠙ Locking..✘ Locking Failed! 
>   [pipenv.exceptions.ResolutionFailure]:   File "/home/varnie/.local/share/virtualenvs/serverless-victoria-TnhmQsN6/lib/python3.8/site-packages/pipenv/resolver.py", line 61, in resolve
>   [pipenv.exceptions.ResolutionFailure]:       return resolve_deps(
>   [pipenv.exceptions.ResolutionFailure]:   File "/home/varnie/.local/share/virtualenvs/serverless-victoria-TnhmQsN6/lib/python3.8/site-packages/pipenv/utils.py", line 718, in resolve_deps
>   [pipenv.exceptions.ResolutionFailure]:       resolved_tree, hashes, markers_lookup, resolver = actually_resolve_deps(
>   [pipenv.exceptions.ResolutionFailure]:   File "/home/varnie/.local/share/virtualenvs/serverless-victoria-TnhmQsN6/lib/python3.8/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
>   [pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
>   [pipenv.exceptions.ResolutionFailure]:   File "/home/varnie/.local/share/virtualenvs/serverless-victoria-TnhmQsN6/lib/python3.8/site-packages/pipenv/utils.py", line 395, in resolve
>   [pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
>   [pipenv.exceptions.ResolutionFailure]:       pipenv.exceptions.ResolutionFailure: ERROR: ERROR: Could not find a version that matches msal<2.0.0,>=1.3.0,~=1.0.0
>   [pipenv.exceptions.ResolutionFailure]:       Tried: 0.1.0, 0.1.0, 0.2.0, 0.2.0, 0.3.0, 0.3.0, 0.3.1, 0.3.1, 0.4.0, 0.4.0, 0.4.1, 0.4.1, 0.5.0, 0.5.0, 0.5.1, 0.5.1, 0.6.0, 0.6.0, 0.6.1, 0.6.1, 0.7.0, 0.7.0, 0.8.0, 0.8.0, 0.8.0, 0.9.0, 0.9.0, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.4.1, 1.4.1, 1.4.2, 1.4.2, 1.4.3, 1.4.3, 1.5.0, 1.5.0
>   [pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
>     First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
>    Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
>     Hint: try $ pipenv lock --pre if it is a pre-release dependency.
>   ERROR: ERROR: Could not find a version that matches msal<2.0.0,>=1.3.0,~=1.0.0
>   Tried: 0.1.0, 0.1.0, 0.2.0, 0.2.0, 0.3.0, 0.3.0, 0.3.1, 0.3.1, 0.4.0, 0.4.0, 0.4.1, 0.4.1, 0.5.0, 0.5.0, 0.5.1, 0.5.1, 0.6.0, 0.6.0, 0.6.1, 0.6.1, 0.7.0, 0.7.0, 0.8.0, 0.8.0, 0.8.0, 0.9.0, 0.9.0, 1.0.0, 1.0.0, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 1.4.0, 1.4.0, 1.4.1, 1.4.1, 1.4.2, 1.4.2, 1.4.3, 1.4.3, 1.5.0, 1.5.0
>   There are incompatible versions in the resolved dependencies.

**Comment by varnie** [comment]
It occurs while resolving the Victoria dependencies. Any chance these settings should be modified?
I examined the Victoria's `poetry.lock` and it seems it has so much various `msal` package versions mentioned.
I am not sure why it was written this way, maybe there's something crucial? 

Anyway, something is wrong along these lines.
For example:
`msal = ">=1.0.0,<1.1.0"`
`msal = ">=1.0.0,<2.0.0"`
`msal = ">=0.4.1,<2.0.0"`

My suggestion is to modify this `poetry.lock` (it comes from the Victoria repository, not this one) and see which `msal` version is needed, actually.

**Comment by varnie** [comment]
May be relevant: https://github.com/Azure/azure-cli/issues/15212

**Comment by AshKapow** [comment]
PR completed for Victoria repo

**Comment by varnie** [comment]
@AshKapow hmm, it still fails with this error:
  

> ERROR: ERROR: Could not find a version that matches msal<2.0.0,>=1.3.0,~=1.0.0

Tried to perform `serverless deploy` in my work-in-progress CD github workflow:
https://github.com/varnie/serverless-victoria/runs/1186667864?check_suite_focus=true

**Comment by AshKapow** [comment]
@varnie correct me if I'm wrong, but this is resolved now?

**Comment by varnie** [comment]
> @varnie correct me if I'm wrong, but this is resolved now?

@AshKapow yes, it is resolved.
